### ISSUE TITLE
Be able to enable/disable label while it's in "Unused labels"

### ISSUE THREAD

**Issue by Sargeanthost** [kurrycat2004/MpkMod#16]

**Comment by Sargeanthost** [comment]
Also don't reset toggle sprint when you fly and land.

**Comment by kurrycat2004** [comment]
toggle sprint?

**Comment by kurrycat2004** [comment]
oh i see

**Comment by Sargeanthost** [comment]
> toggle sprint?

sorry I replied to the wrong issue lol, my point still stands though sorry
