### ISSUE TITLE
Add highest speed label

### ISSUE THREAD

**Issue by Sargeanthost** [kurrycat2004/MpkMod#18]
It would be good to know your max speed achieved.

This could be in the same structure as the speed label but instead of current speed its max speed:

`Max speed: 0.3000/0.0000/.2000`

**Comment by kurrycat2004** [comment]
But then the question would be, when does it reset?

**Comment by kurrycat2004** [comment]
When you stop moving?

**Comment by Sargeanthost** [comment]
a command, like clearlb

**Comment by Sargeanthost** [comment]
The point is that it doesn't reset often because I would like to spend some time with it on my screen

**Comment by kurrycat2004** [comment]
Okay ill add it with a clear command and a config option to enable auto clear when stopping moving
