### ISSUE TITLE
Can't set lb with piston head on block

### ISSUE THREAD

**Issue by Sargeanthost** [kurrycat2004/MpkMod#30]
Tried to setlb on an egg with a piston head on it, doesn't work.

**Comment by kurrycat2004** [comment]
how did you try to setlb? with coords, target or just /mpk setlb

**Comment by kurrycat2004** [comment]
also you cant land on an egg with a piston head on top

**Comment by Sargeanthost** [comment]
> also you cant land on an egg with a piston head on top

no I mean like rotated. and setlb with no target

**Comment by kurrycat2004** [comment]
it probably works how it should because what setlb does is it takes the block .001 below the player position. and because of that it only works if the middle of your hitbox is on the block

**Comment by Sargeanthost** [comment]
> it probably works how it should because what setlb does is it takes the block .001 below the player position. and because of that it only works if the middle of your hitbox is on the block

then it's not working as intended

**Comment by kurrycat2004** [comment]
can you maybe send a screenshot or something i could reproduce it with?

**Comment by Sargeanthost** [comment]
> > it probably works how it should because what setlb does is it takes the block .001 below the player position. and because of that it only works if the middle of your hitbox is on the block
> 
> then it's not working as intended

I was wrong, I'm not over the middle

**Comment by kurrycat2004** [comment]
okay
