### ISSUE TITLE
Better offset 

### ISSUE THREAD

**Issue by hungtik** [kurrycat2004/MpkMod#54]
When I make a jump, the offset uses the magnitude of the sum of vector of 2 facing's offset
Make an option that allows the offset to take the smaller offset value from 2 facings' offset
i.e, if a make a jump on X by .006 and Z on .004
instead of showing the offset value as .00721(vector sum), make it show as .004  (z facing has smaller offset value)

**Comment by kurrycat2004** [comment]
you can already do that if you specify the axis in setlb (/mpk setlb x for example)
also there are labels for offset x and offset z.
only the pb shows the total distance
