### ISSUE TITLE
Camera get reset during tp

### ISSUE THREAD

**Issue by Kinshoop** [kurrycat2004/MpkMod#73]
I'm using one macro for several jumps in a row, and when I'm tp to the next jump, my facing goes to 00. 

https://user-images.githubusercontent.com/82682248/115087484-8682a700-9f0e-11eb-8649-757f1cf5c9e7.mp4

**Comment by kurrycat2004** [comment]
do you specify yaw and pitch in the teleport command

**Comment by Kinshoop** [comment]
yes, when I use the command without macro it works

**Comment by Kinshoop** [comment]
I think this is because since version 3.0, the mpk prevents us from moving our camera during a macro

**Comment by kurrycat2004** [comment]
you can disable that. do /mpk config and enable allowMouseMovement. if you are on mac os dont do that because it will crash your game but edit the setting in the file directly, which is located at .minecraft/config/mpkmod.cfg and do /mpk reloadconfig

**Comment by Kinshoop** [comment]
Oh ok thanks ! it works now, sorry for the inconvenience
