### ISSUE TITLE
Custom Discord RPC

### ISSUE THREAD

**Issue by lyxbyte001** [kurrycat2004/MpkMod#9]
enhancement xd

make a discord rich presence bec why not

shows:
1. if ur on sp or on mp (with server ip)
2. time elapsed
3. custom logo (big image)

once omega pk api is out:
a. have it show what course ur playing on with id (can be toggleable)
b. in addition to 3. the small image can show if ur on build mode or verify mode (in that case show what level ur verifying) or play mode

cant think of more right now xD

**Comment by kurrycat2004** [comment]
YAAAA

**Comment by kurrycat2004** [comment]
But i need a logo first
